In [1]:
# Jayampathy Balasuriya - COMScDS242P-009@student.nibm.lk
# 17-7-2025

In [2]:
import torch

# Tensor Exercises

# 1. Tensor Creation

In [3]:
# Create a tensor of shape (5, 3) filled with random values.
tensor = torch.rand(5, 3) # 5 rows and 3 columns
print(tensor)

tensor([[0.3741, 0.6848, 0.4528],
        [0.8574, 0.7010, 0.7310],
        [0.4453, 0.0719, 0.3491],
        [0.8789, 0.5652, 0.1197],
        [0.0942, 0.3120, 0.1334]])


In [4]:
# Create a tensor of shape (2, 4) filled with ones.
tensor = torch.ones(2,4)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [5]:
# Create a tensor from a list [5, 10, 15, 20].
tensor = torch.tensor([5, 10, 15, 20])
print(tensor)

tensor([ 5, 10, 15, 20])


In [6]:
# Create a tensor to represent an image that has width of 8, height of 6, and 3 channels.
tensor = torch.randint(0, 10, (3, 6, 8))
print(tensor)

tensor([[[0, 8, 4, 0, 8, 4, 0, 0],
         [2, 8, 8, 8, 5, 5, 5, 0],
         [8, 5, 5, 9, 8, 7, 0, 4],
         [2, 1, 7, 0, 8, 9, 2, 1],
         [6, 9, 2, 8, 7, 5, 4, 6],
         [9, 0, 2, 8, 1, 4, 0, 4]],

        [[5, 4, 2, 3, 6, 4, 3, 7],
         [0, 9, 8, 9, 8, 7, 1, 8],
         [2, 3, 6, 4, 9, 5, 7, 4],
         [6, 5, 1, 7, 3, 6, 7, 7],
         [5, 2, 5, 8, 3, 0, 4, 9],
         [2, 1, 3, 6, 3, 6, 2, 8]],

        [[0, 0, 1, 9, 4, 4, 2, 2],
         [3, 7, 3, 9, 0, 3, 4, 6],
         [8, 1, 6, 9, 7, 0, 9, 6],
         [9, 4, 2, 4, 0, 1, 6, 4],
         [9, 0, 3, 5, 5, 6, 6, 4],
         [3, 6, 9, 4, 0, 9, 2, 8]]])


# 2. Tensor Indexing and Slicing

In [7]:
# Create a tensor tensor of shape (3, 4) with values ranging from 10 to 22.
tensor = torch.arange(10, 22).reshape(3, 4)
print(tensor)


tensor([[10, 11, 12, 13],
        [14, 15, 16, 17],
        [18, 19, 20, 21]])


In [8]:
# Access the element at the second row, third column.
print(tensor[1, 2]) # 0 index row and column

tensor(16)


In [9]:
# Print the second row.
print(tensor[1])

tensor([14, 15, 16, 17])


In [10]:
# Print the first two columns.
print(tensor[:, 0:2])

tensor([[10, 11],
        [14, 15],
        [18, 19]])


# 3. Tensor Arithmetic Operations

In [11]:
# Create two tensors tensor_a and tensor_b of shape (3, 3) with random int values values.
tensor_a = torch.randint(0, 10, (3, 3))
tensor_b = torch.randint(0, 10, (3, 3))
print(tensor_a)
print(tensor_b)

tensor([[3, 6, 8],
        [3, 4, 1],
        [2, 3, 0]])
tensor([[3, 0, 1],
        [3, 2, 8],
        [0, 5, 2]])


In [12]:
# Perform element-wise addition.
print(tensor_a + tensor_b)

tensor([[6, 6, 9],
        [6, 6, 9],
        [2, 8, 2]])


In [13]:
# Perform element-wise multiplication.
print(tensor_a * tensor_b)

tensor([[ 9,  0,  8],
        [ 9,  8,  8],
        [ 0, 15,  0]])


In [14]:
# Subtract tensor_b from tensor_a.
print(tensor_a - tensor_b)

tensor([[ 0,  6,  7],
        [ 0,  2, -7],
        [ 2, -2, -2]])


# 4. Tensor Aggregation Operations

In [15]:
# Create a tensor tensor of shape (3, 3) with values ranging from 1 to 9.
tensor = torch.arange(1, 10).reshape(3, 3)
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [16]:
# Compute the sum of all elements.
print(tensor.sum())

tensor(45)


In [17]:
# Compute the mean of all elements.
print(tensor.float().mean())

tensor(5.)


In [18]:
# Find the maximum and minimum values.
print(tensor.max())
print(tensor.min())

tensor(9)
tensor(1)


In [19]:
# Compute the sum along the rows.
print(tensor.sum(dim=1))

tensor([ 6, 15, 24])


In [20]:
# Compute the mean along the columns.
print(tensor.float().mean(dim=0))

tensor([4., 5., 6.])


# 5. Tensor Reshaping Operations

In [21]:
# Create a tensor tensor of shape (2, 3, 4) with random values.
tensor = torch.randint(0,10, (2, 3, 4))
print(tensor)

tensor([[[5, 0, 2, 5],
         [9, 7, 7, 6],
         [4, 7, 4, 5]],

        [[3, 2, 3, 2],
         [4, 5, 1, 3],
         [2, 8, 9, 2]]])


In [22]:
# Reshape the tensor to (4, 6).
print(tensor.reshape(4, 6))

tensor([[5, 0, 2, 5, 9, 7],
        [7, 6, 4, 7, 4, 5],
        [3, 2, 3, 2, 4, 5],
        [1, 3, 2, 8, 9, 2]])


In [23]:
# Transpose the tensor (swap the first and second dimensions).

# print the tensor 0 dimension
print(tensor[0])
# print the tensor 1 dimension
print(tensor[1])

print(tensor.transpose(0, 1))

tensor([[5, 0, 2, 5],
        [9, 7, 7, 6],
        [4, 7, 4, 5]])
tensor([[3, 2, 3, 2],
        [4, 5, 1, 3],
        [2, 8, 9, 2]])
tensor([[[5, 0, 2, 5],
         [3, 2, 3, 2]],

        [[9, 7, 7, 6],
         [4, 5, 1, 3]],

        [[4, 7, 4, 5],
         [2, 8, 9, 2]]])


Let's understand how this works:

tensor: This is the tensor you created earlier with the shape (2, 3, 4). It has three dimensions.
.transpose(0, 1): This is a PyTorch method that swaps two specified dimensions of the tensor. In this case, it's swapping the dimension at index 0 with the dimension at index 1.
So, if your original tensor has a shape of (dimension 0, dimension 1, dimension 2), transposing dimensions 0 and 1 will result in a new tensor with the shape (dimension 1, dimension 0, dimension 2).

In your specific example, the original tensor has a shape of (2, 3, 4). After transpose(0, 1), the resulting tensor will have a shape of (3, 2, 4). The elements are rearranged so that what was in the first dimension is now in the second, and vice versa.

In [24]:
# Flatten the tensor to a 1D tensor.
print(tensor.flatten())

tensor([5, 0, 2, 5, 9, 7, 7, 6, 4, 7, 4, 5, 3, 2, 3, 2, 4, 5, 1, 3, 2, 8, 9, 2])


# 6. Tensor Broadcasting

In [25]:
# Create a tensor tensor_a of shape (2, 3) with values ranging from 1 to 6.
tensor_a = torch.arange(1, 7).reshape(2, 3)
print(tensor_a)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [26]:
# Create a tensor tensor_b of shape (1, 3) with values [1, 2, 3].
tensor_b = torch.tensor([1, 2, 3])
print(tensor_b)

tensor([1, 2, 3])


In [27]:
# Perform broadcasting addition.
print(tensor_a + tensor_b)

tensor([[2, 4, 6],
        [5, 7, 9]])


In [28]:
# Create a tensor tensor_c of shape (3, 1) with values [1, 2, 3].
tensor_c = torch.tensor([[1], [2], [3]])
print(tensor_c)

tensor([[1],
        [2],
        [3]])


In [30]:
# Perform broadcasting multiplication.
print(tensor_a * tensor_b)

tensor([[ 1,  4,  9],
        [ 4, 10, 18]])


# 7. Tensor Device Management

In [2]:
# Create a tensor of shape (3, 3) with random values and move it to GPU (if available).
tensor = torch.rand(3,3)
print(tensor)

tensor([[0.8258, 0.7219, 0.6414],
        [0.9845, 0.1028, 0.0528],
        [0.0563, 0.9363, 0.7374]])


In [ ]:
# Verify if the tensor is on GPU.
# Move the tensor back to CPU.

# 8. Tensor Cloning and Detaching

In [5]:
# Create a tensor tensor of shape (3,) with values [1, 2, 3] and set requires_grad=True.
tensor = torch.tensor([[1.0], [2.0], [3.0]], requires_grad=True)
print(tensor)

tensor([[1.],
        [2.],
        [3.]], requires_grad=True)


When you set requires_grad=True for a tensor, you are telling PyTorch to track all operations performed on that tensor. This is essential for calculating gradients during the backpropagation phase of training neural networks.

In simpler terms:

Tracking Operations: PyTorch builds a computation graph in the background as you perform operations on tensors with requires_grad=True. This graph records how the output of an operation was computed from its inputs.
Gradient Calculation: After you perform a forward pass (computing the output of your model), you can call the .backward() method on the output tensor. PyTorch then uses the computation graph to automatically calculate the gradients of the output with respect to the input tensors that have requires_grad=True.
This is fundamental for training models because gradient descent and other optimization algorithms rely on these gradients to update the model's parameters (which are typically tensors with requires_grad=True) and minimize the loss function.

In the context of your example, setting requires_grad=True on the tensor means that if you were to perform further operations on this tensor and then call .backward() on the final result, PyTorch would be able to calculate the gradient of that result with respect to this original tensor.

In [6]:
# Clone the tensor and print the cloned tensor.
cloned_tensor = tensor.clone()
print(cloned_tensor)

tensor([[1.],
        [2.],
        [3.]], grad_fn=<CloneBackward0>)


In [7]:
# Detach the tensor from the computation graph and print the detached tensor.
detached_tensor = tensor.detach()
print(detached_tensor)

tensor([[1.],
        [2.],
        [3.]])


# 9. High Dimensional Tensors

In [8]:
# Create a 4D tensor tensor of shape (2, 3, 4, 5) with random values.
tensor = torch.rand(2, 3, 4, 5)
print(tensor)

tensor([[[[0.3168, 0.0350, 0.4393, 0.4678, 0.8654],
          [0.8073, 0.2970, 0.2523, 0.4506, 0.8626],
          [0.4004, 0.1775, 0.2699, 0.7478, 0.5480],
          [0.2711, 0.7475, 0.8193, 0.4575, 0.2122]],

         [[0.3492, 0.8130, 0.5617, 0.0230, 0.9386],
          [0.4573, 0.2428, 0.9297, 0.2131, 0.2522],
          [0.7214, 0.8602, 0.8291, 0.1014, 0.8952],
          [0.3062, 0.4652, 0.7291, 0.3265, 0.9205]],

         [[0.5730, 0.7389, 0.3276, 0.8817, 0.8999],
          [0.7690, 0.6805, 0.7639, 0.0084, 0.6544],
          [0.7010, 0.4528, 0.3284, 0.0602, 0.9200],
          [0.0963, 0.4011, 0.2398, 0.1469, 0.1650]]],


        [[[0.7665, 0.2168, 0.6868, 0.4246, 0.5621],
          [0.1351, 0.0740, 0.8869, 0.1666, 0.7082],
          [0.2451, 0.4497, 0.0547, 0.7272, 0.6907],
          [0.0739, 0.1089, 0.5502, 0.1549, 0.9050]],

         [[0.7532, 0.5375, 0.3175, 0.6618, 0.1881],
          [0.8770, 0.4594, 0.2216, 0.0816, 0.7655],
          [0.9471, 0.6633, 0.3773, 0.6388, 0.4646],
  

In [11]:
# Print the shape of the tensor.
print(tensor.shape)
print(tensor.size())

torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])


In [10]:
# Access the element at position (1, 2, 3, 4).
print(tensor[1, 2, 3, 4])

tensor(0.4555)


In [13]:
# Slice and print the first two elements along the first dimension.
sliced_tensor = tensor[:2, :, :, :]
print(sliced_tensor)

tensor([[[[0.3168, 0.0350, 0.4393, 0.4678, 0.8654],
          [0.8073, 0.2970, 0.2523, 0.4506, 0.8626],
          [0.4004, 0.1775, 0.2699, 0.7478, 0.5480],
          [0.2711, 0.7475, 0.8193, 0.4575, 0.2122]],

         [[0.3492, 0.8130, 0.5617, 0.0230, 0.9386],
          [0.4573, 0.2428, 0.9297, 0.2131, 0.2522],
          [0.7214, 0.8602, 0.8291, 0.1014, 0.8952],
          [0.3062, 0.4652, 0.7291, 0.3265, 0.9205]],

         [[0.5730, 0.7389, 0.3276, 0.8817, 0.8999],
          [0.7690, 0.6805, 0.7639, 0.0084, 0.6544],
          [0.7010, 0.4528, 0.3284, 0.0602, 0.9200],
          [0.0963, 0.4011, 0.2398, 0.1469, 0.1650]]],


        [[[0.7665, 0.2168, 0.6868, 0.4246, 0.5621],
          [0.1351, 0.0740, 0.8869, 0.1666, 0.7082],
          [0.2451, 0.4497, 0.0547, 0.7272, 0.6907],
          [0.0739, 0.1089, 0.5502, 0.1549, 0.9050]],

         [[0.7532, 0.5375, 0.3175, 0.6618, 0.1881],
          [0.8770, 0.4594, 0.2216, 0.0816, 0.7655],
          [0.9471, 0.6633, 0.3773, 0.6388, 0.4646],
  

In [14]:
# Sum all elements in the tensor.
print(tensor.sum().item())

tensor(57.7419)


In [15]:
# Compute the mean along the third dimension.
print(tensor.mean(dim=2))

tensor([[[0.4489, 0.3143, 0.4452, 0.5309, 0.6221],
         [0.4585, 0.5953, 0.7624, 0.1660, 0.7516],
         [0.5348, 0.5683, 0.4149, 0.2743, 0.6598]],

        [[0.3052, 0.2123, 0.5446, 0.3683, 0.7165],
         [0.8552, 0.4324, 0.2746, 0.4163, 0.5973],
         [0.4093, 0.4426, 0.3084, 0.6858, 0.3192]]])


# 10. Combining Tensor Operations

In [4]:
# Create two tensors tensor_a and tensor_b of shape (2, 3, 4) with random values.
tensor_a = torch.randint(0,10, (2, 3, 4))
tensor_b = torch.randint(0,10, (2, 3, 4))

print(tensor_a)
print(tensor_b)

tensor([[[0, 2, 8, 4],
         [2, 1, 0, 0],
         [8, 5, 2, 6]],

        [[5, 2, 8, 9],
         [9, 6, 6, 0],
         [2, 0, 3, 1]]])
tensor([[[5, 1, 4, 1],
         [3, 9, 3, 2],
         [4, 5, 3, 1]],

        [[4, 8, 6, 5],
         [9, 0, 0, 4],
         [3, 9, 7, 9]]])


In [5]:
# Add the two tensors.
tensor_c = tensor_a + tensor_b
print(tensor_c)

tensor([[[ 5,  3, 12,  5],
         [ 5, 10,  3,  2],
         [12, 10,  5,  7]],

        [[ 9, 10, 14, 14],
         [18,  6,  6,  4],
         [ 5,  9, 10, 10]]])


In [6]:
# Multiply the resulting tensor by 2.
tensor_c.mul(2)

tensor([[[10,  6, 24, 10],
         [10, 20,  6,  4],
         [24, 20, 10, 14]],

        [[18, 20, 28, 28],
         [36, 12, 12,  8],
         [10, 18, 20, 20]]])

In [7]:
# Reshape the tensor to (4, 6).
tensor_c.reshape(4, 6)

tensor([[ 5,  3, 12,  5,  5, 10],
        [ 3,  2, 12, 10,  5,  7],
        [ 9, 10, 14, 14, 18,  6],
        [ 6,  4,  5,  9, 10, 10]])

In [8]:
# Compute the sum along the columns.
tensor_c.sum(dim=0)

tensor([[14, 13, 26, 19],
        [23, 16,  9,  6],
        [17, 19, 15, 17]])

-------------------------------------------- END ----------------------------------------------